import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import "./main.855225c5.css"
import Head from "next/head";
import Script from 'next/script'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link href="/widget/static/css/main.855225c5.css" rel="stylesheet" />
      </Head>
        <Script defer src="/widget/static/js/main.76bc4272.js"></Script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
